services:
  db:
    container_name: nemesis-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nemesis
      MYSQL_DATABASE: nemesis
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pnemesis",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
