services:
  # MySQL service for development
  mysql:
    image: mysql:9.3
    container_name: nemesis-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nemesis
      - MYSQL_USER=nemesis
      - MYSQL_PASSWORD=nemesis
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
