services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
    container_name: nemesis-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: pnpm dev
    restart: unless-stopped
    depends_on:
      - mysql

  # Production service
  app-prod:
    build:
      context: .
      target: production
    container_name: nemesis-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped

  # MySQL service for development
  mysql:
    image: mysql:8.4
    container_name: nemesis-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nemesis
      - MYSQL_USER=nemesis
      - MYSQL_PASSWORD=nemesis
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
